# dbt_project.yml
# Manufacturing Semiconductors dbt Project
# By Gideon Fernandez at Velocity Sense
# https://www.velocitysense.com

name: 'manufacturing_semiconductors_dbt'
version: '1.0.0'
config-version: 2

# dbt Cloud
dbt-cloud:
    project-id: 402943

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  manufacturing_semiconductors_dbt:
    +materialized: view

# Project variables
vars:
  warn_threshold: 0.90
  fail_threshold: 0.85
  high_energy_threshold: 1200
